### ISSUE TITLE
Change Customization Group?

### ISSUE THREAD

**Issue by sshaw** [xuchunyang/github-notifier.el#11]
Currently it uses its own group so you get this when customizing: 

<img width="523" alt="github-notifier" src="https://cloud.githubusercontent.com/assets/17570/26766770/d1479938-4965-11e7-961b-90a637c52ddb.png">

Was this intentional? If not, why not put this under a common customization group like Communication?

**Comment by xuchunyang** [comment]
Thanks for your suggestion.
