### ISSUE TITLE
Failed Connection Does Not Restore Timer

### ISSUE THREAD

**Issue by sshaw** [xuchunyang/github-notifier.el#7]
When `url-retrieve` has a problem connecting to :octocat: `github-notifier-update-cb` is not called and the timer is never reset.

Here's the error I received when I lost connectivity:

```
Opening TLS connection to `api.github.com'...failed
Error running timer `github-notifier-update': (error "Could not create connection to api.github.com:443")
```

I assume it's due to the fact that [`url-retrieve`'s `SILENT` option has been set to `t`](https://github.com/xuchunyang/github-notifier.el/blob/ab906f66f31b4d2ddeb4464d052cbf2d493c89cf/github-notifier.el#L170). Though depending on the error `CALLBACK` may never be called even if `SILENT` is `nil`, Maybe an `unwind-protect` call can be used for these cases.

**Comment by xuchunyang** [comment]
I pushed a commit to try to resolve this issue.  Feel free to reopen if you're not satisfied with the fix.

**Comment by sshaw** [comment]
Looks good!
